/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportThankYouRouteImport } from './routes/support-thank-you'
import { Route as SupportLoginRouteImport } from './routes/support-login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RhrnIndexRouteImport } from './routes/rhrn.index'
import { Route as DiscoverIndexRouteImport } from './routes/discover.index'
import { Route as CommunityMapIndexRouteImport } from './routes/community-map.index'
import { Route as CommunityEventsIndexRouteImport } from './routes/community-events.index'
import { Route as RhrnRequestsRouteImport } from './routes/rhrn.requests'
import { Route as RhrnChatsRouteImport } from './routes/rhrn.chats'
import { Route as RhrnIdRouteImport } from './routes/rhrn.$id'
import { Route as DiscoverApplyRouteImport } from './routes/discover.apply'
import { Route as CommunityMapApplyRouteImport } from './routes/community-map.apply'
import { Route as CommunityEventsNewRouteImport } from './routes/community-events.new'
import { Route as CommunityEventsIdRouteImport } from './routes/community-events.$id'
import { Route as RhrnChatIdRouteImport } from './routes/rhrn.chat.$id'
import { Route as DiscoverSafeSpaceIdRouteImport } from './routes/discover.safe-space.$id'

const SupportThankYouRoute = SupportThankYouRouteImport.update({
  id: '/support-thank-you',
  path: '/support-thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportLoginRoute = SupportLoginRouteImport.update({
  id: '/support-login',
  path: '/support-login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RhrnIndexRoute = RhrnIndexRouteImport.update({
  id: '/rhrn/',
  path: '/rhrn/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMapIndexRoute = CommunityMapIndexRouteImport.update({
  id: '/community-map/',
  path: '/community-map/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsIndexRoute = CommunityEventsIndexRouteImport.update({
  id: '/community-events/',
  path: '/community-events/',
  getParentRoute: () => rootRouteImport,
} as any)
const RhrnRequestsRoute = RhrnRequestsRouteImport.update({
  id: '/rhrn/requests',
  path: '/rhrn/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RhrnChatsRoute = RhrnChatsRouteImport.update({
  id: '/rhrn/chats',
  path: '/rhrn/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const RhrnIdRoute = RhrnIdRouteImport.update({
  id: '/rhrn/$id',
  path: '/rhrn/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverApplyRoute = DiscoverApplyRouteImport.update({
  id: '/discover/apply',
  path: '/discover/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMapApplyRoute = CommunityMapApplyRouteImport.update({
  id: '/community-map/apply',
  path: '/community-map/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsNewRoute = CommunityEventsNewRouteImport.update({
  id: '/community-events/new',
  path: '/community-events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsIdRoute = CommunityEventsIdRouteImport.update({
  id: '/community-events/$id',
  path: '/community-events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RhrnChatIdRoute = RhrnChatIdRouteImport.update({
  id: '/rhrn/chat/$id',
  path: '/rhrn/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverSafeSpaceIdRoute = DiscoverSafeSpaceIdRouteImport.update({
  id: '/discover/safe-space/$id',
  path: '/discover/safe-space/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/support-login': typeof SupportLoginRoute
  '/support-thank-you': typeof SupportThankYouRoute
  '/community-events/$id': typeof CommunityEventsIdRoute
  '/community-events/new': typeof CommunityEventsNewRoute
  '/community-map/apply': typeof CommunityMapApplyRoute
  '/discover/apply': typeof DiscoverApplyRoute
  '/rhrn/$id': typeof RhrnIdRoute
  '/rhrn/chats': typeof RhrnChatsRoute
  '/rhrn/requests': typeof RhrnRequestsRoute
  '/community-events/': typeof CommunityEventsIndexRoute
  '/community-map/': typeof CommunityMapIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/rhrn/': typeof RhrnIndexRoute
  '/discover/safe-space/$id': typeof DiscoverSafeSpaceIdRoute
  '/rhrn/chat/$id': typeof RhrnChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/support-login': typeof SupportLoginRoute
  '/support-thank-you': typeof SupportThankYouRoute
  '/community-events/$id': typeof CommunityEventsIdRoute
  '/community-events/new': typeof CommunityEventsNewRoute
  '/community-map/apply': typeof CommunityMapApplyRoute
  '/discover/apply': typeof DiscoverApplyRoute
  '/rhrn/$id': typeof RhrnIdRoute
  '/rhrn/chats': typeof RhrnChatsRoute
  '/rhrn/requests': typeof RhrnRequestsRoute
  '/community-events': typeof CommunityEventsIndexRoute
  '/community-map': typeof CommunityMapIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/rhrn': typeof RhrnIndexRoute
  '/discover/safe-space/$id': typeof DiscoverSafeSpaceIdRoute
  '/rhrn/chat/$id': typeof RhrnChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/support-login': typeof SupportLoginRoute
  '/support-thank-you': typeof SupportThankYouRoute
  '/community-events/$id': typeof CommunityEventsIdRoute
  '/community-events/new': typeof CommunityEventsNewRoute
  '/community-map/apply': typeof CommunityMapApplyRoute
  '/discover/apply': typeof DiscoverApplyRoute
  '/rhrn/$id': typeof RhrnIdRoute
  '/rhrn/chats': typeof RhrnChatsRoute
  '/rhrn/requests': typeof RhrnRequestsRoute
  '/community-events/': typeof CommunityEventsIndexRoute
  '/community-map/': typeof CommunityMapIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/rhrn/': typeof RhrnIndexRoute
  '/discover/safe-space/$id': typeof DiscoverSafeSpaceIdRoute
  '/rhrn/chat/$id': typeof RhrnChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/profile'
    | '/register'
    | '/support-login'
    | '/support-thank-you'
    | '/community-events/$id'
    | '/community-events/new'
    | '/community-map/apply'
    | '/discover/apply'
    | '/rhrn/$id'
    | '/rhrn/chats'
    | '/rhrn/requests'
    | '/community-events/'
    | '/community-map/'
    | '/discover/'
    | '/rhrn/'
    | '/discover/safe-space/$id'
    | '/rhrn/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/profile'
    | '/register'
    | '/support-login'
    | '/support-thank-you'
    | '/community-events/$id'
    | '/community-events/new'
    | '/community-map/apply'
    | '/discover/apply'
    | '/rhrn/$id'
    | '/rhrn/chats'
    | '/rhrn/requests'
    | '/community-events'
    | '/community-map'
    | '/discover'
    | '/rhrn'
    | '/discover/safe-space/$id'
    | '/rhrn/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/profile'
    | '/register'
    | '/support-login'
    | '/support-thank-you'
    | '/community-events/$id'
    | '/community-events/new'
    | '/community-map/apply'
    | '/discover/apply'
    | '/rhrn/$id'
    | '/rhrn/chats'
    | '/rhrn/requests'
    | '/community-events/'
    | '/community-map/'
    | '/discover/'
    | '/rhrn/'
    | '/discover/safe-space/$id'
    | '/rhrn/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SupportLoginRoute: typeof SupportLoginRoute
  SupportThankYouRoute: typeof SupportThankYouRoute
  CommunityEventsIdRoute: typeof CommunityEventsIdRoute
  CommunityEventsNewRoute: typeof CommunityEventsNewRoute
  CommunityMapApplyRoute: typeof CommunityMapApplyRoute
  DiscoverApplyRoute: typeof DiscoverApplyRoute
  RhrnIdRoute: typeof RhrnIdRoute
  RhrnChatsRoute: typeof RhrnChatsRoute
  RhrnRequestsRoute: typeof RhrnRequestsRoute
  CommunityEventsIndexRoute: typeof CommunityEventsIndexRoute
  CommunityMapIndexRoute: typeof CommunityMapIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  RhrnIndexRoute: typeof RhrnIndexRoute
  DiscoverSafeSpaceIdRoute: typeof DiscoverSafeSpaceIdRoute
  RhrnChatIdRoute: typeof RhrnChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support-thank-you': {
      id: '/support-thank-you'
      path: '/support-thank-you'
      fullPath: '/support-thank-you'
      preLoaderRoute: typeof SupportThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-login': {
      id: '/support-login'
      path: '/support-login'
      fullPath: '/support-login'
      preLoaderRoute: typeof SupportLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhrn/': {
      id: '/rhrn/'
      path: '/rhrn'
      fullPath: '/rhrn/'
      preLoaderRoute: typeof RhrnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-map/': {
      id: '/community-map/'
      path: '/community-map'
      fullPath: '/community-map/'
      preLoaderRoute: typeof CommunityMapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-events/': {
      id: '/community-events/'
      path: '/community-events'
      fullPath: '/community-events/'
      preLoaderRoute: typeof CommunityEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhrn/requests': {
      id: '/rhrn/requests'
      path: '/rhrn/requests'
      fullPath: '/rhrn/requests'
      preLoaderRoute: typeof RhrnRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhrn/chats': {
      id: '/rhrn/chats'
      path: '/rhrn/chats'
      fullPath: '/rhrn/chats'
      preLoaderRoute: typeof RhrnChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhrn/$id': {
      id: '/rhrn/$id'
      path: '/rhrn/$id'
      fullPath: '/rhrn/$id'
      preLoaderRoute: typeof RhrnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/apply': {
      id: '/discover/apply'
      path: '/discover/apply'
      fullPath: '/discover/apply'
      preLoaderRoute: typeof DiscoverApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-map/apply': {
      id: '/community-map/apply'
      path: '/community-map/apply'
      fullPath: '/community-map/apply'
      preLoaderRoute: typeof CommunityMapApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-events/new': {
      id: '/community-events/new'
      path: '/community-events/new'
      fullPath: '/community-events/new'
      preLoaderRoute: typeof CommunityEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-events/$id': {
      id: '/community-events/$id'
      path: '/community-events/$id'
      fullPath: '/community-events/$id'
      preLoaderRoute: typeof CommunityEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhrn/chat/$id': {
      id: '/rhrn/chat/$id'
      path: '/rhrn/chat/$id'
      fullPath: '/rhrn/chat/$id'
      preLoaderRoute: typeof RhrnChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/safe-space/$id': {
      id: '/discover/safe-space/$id'
      path: '/discover/safe-space/$id'
      fullPath: '/discover/safe-space/$id'
      preLoaderRoute: typeof DiscoverSafeSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SupportLoginRoute: SupportLoginRoute,
  SupportThankYouRoute: SupportThankYouRoute,
  CommunityEventsIdRoute: CommunityEventsIdRoute,
  CommunityEventsNewRoute: CommunityEventsNewRoute,
  CommunityMapApplyRoute: CommunityMapApplyRoute,
  DiscoverApplyRoute: DiscoverApplyRoute,
  RhrnIdRoute: RhrnIdRoute,
  RhrnChatsRoute: RhrnChatsRoute,
  RhrnRequestsRoute: RhrnRequestsRoute,
  CommunityEventsIndexRoute: CommunityEventsIndexRoute,
  CommunityMapIndexRoute: CommunityMapIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  RhrnIndexRoute: RhrnIndexRoute,
  DiscoverSafeSpaceIdRoute: DiscoverSafeSpaceIdRoute,
  RhrnChatIdRoute: RhrnChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
