/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportThankYouRouteImport } from './routes/support-thank-you'
import { Route as SupportLoginRouteImport } from './routes/support-login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityEventsIndexRouteImport } from './routes/community-events.index'
import { Route as CommunityEventsNewRouteImport } from './routes/community-events.new'
import { Route as CommunityEventsIdRouteImport } from './routes/community-events.$id'

const SupportThankYouRoute = SupportThankYouRouteImport.update({
  id: '/support-thank-you',
  path: '/support-thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportLoginRoute = SupportLoginRouteImport.update({
  id: '/support-login',
  path: '/support-login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsIndexRoute = CommunityEventsIndexRouteImport.update({
  id: '/community-events/',
  path: '/community-events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsNewRoute = CommunityEventsNewRouteImport.update({
  id: '/community-events/new',
  path: '/community-events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsIdRoute = CommunityEventsIdRouteImport.update({
  id: '/community-events/$id',
  path: '/community-events/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/support-login': typeof SupportLoginRoute
  '/support-thank-you': typeof SupportThankYouRoute
  '/community-events/$id': typeof CommunityEventsIdRoute
  '/community-events/new': typeof CommunityEventsNewRoute
  '/community-events/': typeof CommunityEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/support-login': typeof SupportLoginRoute
  '/support-thank-you': typeof SupportThankYouRoute
  '/community-events/$id': typeof CommunityEventsIdRoute
  '/community-events/new': typeof CommunityEventsNewRoute
  '/community-events': typeof CommunityEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/support-login': typeof SupportLoginRoute
  '/support-thank-you': typeof SupportThankYouRoute
  '/community-events/$id': typeof CommunityEventsIdRoute
  '/community-events/new': typeof CommunityEventsNewRoute
  '/community-events/': typeof CommunityEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/login'
    | '/profile'
    | '/register'
    | '/support-login'
    | '/support-thank-you'
    | '/community-events/$id'
    | '/community-events/new'
    | '/community-events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/login'
    | '/profile'
    | '/register'
    | '/support-login'
    | '/support-thank-you'
    | '/community-events/$id'
    | '/community-events/new'
    | '/community-events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/login'
    | '/profile'
    | '/register'
    | '/support-login'
    | '/support-thank-you'
    | '/community-events/$id'
    | '/community-events/new'
    | '/community-events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SupportLoginRoute: typeof SupportLoginRoute
  SupportThankYouRoute: typeof SupportThankYouRoute
  CommunityEventsIdRoute: typeof CommunityEventsIdRoute
  CommunityEventsNewRoute: typeof CommunityEventsNewRoute
  CommunityEventsIndexRoute: typeof CommunityEventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support-thank-you': {
      id: '/support-thank-you'
      path: '/support-thank-you'
      fullPath: '/support-thank-you'
      preLoaderRoute: typeof SupportThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-login': {
      id: '/support-login'
      path: '/support-login'
      fullPath: '/support-login'
      preLoaderRoute: typeof SupportLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-events/': {
      id: '/community-events/'
      path: '/community-events'
      fullPath: '/community-events/'
      preLoaderRoute: typeof CommunityEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-events/new': {
      id: '/community-events/new'
      path: '/community-events/new'
      fullPath: '/community-events/new'
      preLoaderRoute: typeof CommunityEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-events/$id': {
      id: '/community-events/$id'
      path: '/community-events/$id'
      fullPath: '/community-events/$id'
      preLoaderRoute: typeof CommunityEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SupportLoginRoute: SupportLoginRoute,
  SupportThankYouRoute: SupportThankYouRoute,
  CommunityEventsIdRoute: CommunityEventsIdRoute,
  CommunityEventsNewRoute: CommunityEventsNewRoute,
  CommunityEventsIndexRoute: CommunityEventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
